all:: git-hoelzro
git-hoelzro:
	git clone https://github.com/hoelzro/awesome-config $@
update::
	cd git-hoelzro; git pull

all:: git-meriadec
git-meriadec:
	git clone https://github.com/meriadec/awesome-sombra $@
update::
	cd git-meriadec; git pull

# this one has nice docs as well: https://github.com/pw4ever/awesome-wm-config
all:: git-pw4ever
git-pw4ever:
	git clone https://github.com/pw4ever/awesome-wm-config $@
update::
	cd git-pw4ever; git pull


all:: awesome-freedesktop
freedesktop:
	git clone https://github.com/copycat-killer/awesome-freedesktop $@
update::
	cd freedesktop; git pull
