all:: git-hoelzro/.git/HEAD
git-hoelzro/.git/HEAD:
	git clone https://github.com/hoelzro/awesome-config hoelzro
update::
	cd git-hoelzro; git pull

all:: git-meriadec/.git/HEAD
git-meriadec/.git/HEAD:
	git clone https://github.com/meriadec/awesome-sombra meriadoc
update::
	cd git-meriadec; git pull

# this one has nice docs as well: https://github.com/pw4ever/awesome-wm-config
all:: git-pw4ever/.git/HEAD
git-pw4ever/.git/HEAD:
	git clone https://github.com/pw4ever/awesome-wm-config pw4ever
update::
	cd git-pw4ever; git pull

all:: git-mic92/.git/HEAD
git-mic92/.git/HEAD:
	git clone https://github.com/Mic92/awesome-dotfiles mic92
update::
	cd git-mic92; git pull

all:: git-material/.git/HEAD
git-material/.git/HEAD:
	git clone https://github.com/PapyElGringo/material-awesome git-material
update::
	cd git-material; git pull
