#!/usr/bin/python3

import subprocess
import sys, os


def get_output(cmd):
	with open(os.devnull, 'w') as devnull:
		process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=devnull)
	out = process.communicate()[0].decode()
	process.stdout.close()
	return out


out = get_output(['/usr/bin/i3-msg', '[class="%s"] focus' % sys.argv[1]])
if out.find('"success":false') != -1:
	subprocess.call(sys.argv[2:])
